/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Student } from "./interfaces/student";
export { Student } from "./interfaces/student";
export namespace Components {
    interface AppRoot {
    }
    interface StudentForm {
    }
    interface StudentList {
        /**
          * @default []
         */
        "students": Student[];
    }
}
export interface StudentFormCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLStudentFormElement;
}
export interface StudentListCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLStudentListElement;
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLStudentFormElementEventMap {
        "studentAdded": Student;
    }
    interface HTMLStudentFormElement extends Components.StudentForm, HTMLStencilElement {
        addEventListener<K extends keyof HTMLStudentFormElementEventMap>(type: K, listener: (this: HTMLStudentFormElement, ev: StudentFormCustomEvent<HTMLStudentFormElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLStudentFormElementEventMap>(type: K, listener: (this: HTMLStudentFormElement, ev: StudentFormCustomEvent<HTMLStudentFormElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLStudentFormElement: {
        prototype: HTMLStudentFormElement;
        new (): HTMLStudentFormElement;
    };
    interface HTMLStudentListElementEventMap {
        "deleteStudent": number;
        "editStudent": Student;
    }
    interface HTMLStudentListElement extends Components.StudentList, HTMLStencilElement {
        addEventListener<K extends keyof HTMLStudentListElementEventMap>(type: K, listener: (this: HTMLStudentListElement, ev: StudentListCustomEvent<HTMLStudentListElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLStudentListElementEventMap>(type: K, listener: (this: HTMLStudentListElement, ev: StudentListCustomEvent<HTMLStudentListElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLStudentListElement: {
        prototype: HTMLStudentListElement;
        new (): HTMLStudentListElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "student-form": HTMLStudentFormElement;
        "student-list": HTMLStudentListElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
    }
    interface StudentForm {
        "onStudentAdded"?: (event: StudentFormCustomEvent<Student>) => void;
    }
    interface StudentList {
        "onDeleteStudent"?: (event: StudentListCustomEvent<number>) => void;
        "onEditStudent"?: (event: StudentListCustomEvent<Student>) => void;
        /**
          * @default []
         */
        "students"?: Student[];
    }
    interface IntrinsicElements {
        "app-root": AppRoot;
        "student-form": StudentForm;
        "student-list": StudentList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.IntrinsicElements["app-root"] & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "student-form": LocalJSX.IntrinsicElements["student-form"] & JSXBase.HTMLAttributes<HTMLStudentFormElement>;
            "student-list": LocalJSX.IntrinsicElements["student-list"] & JSXBase.HTMLAttributes<HTMLStudentListElement>;
        }
    }
}
